name: Multi-Language CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"

jobs:
  Build:
    name: Build (${{ matrix.language }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [Python, Nodejs]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        if: matrix.language == 'Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies (Python)
        if: matrix.language == 'Python'
        working-directory: back-end
        run: pip install -r requirements.txt

      - name: Build (Python)
        if: matrix.language == 'Python'
        working-directory: back-end
        run: python -m py_compile $(find app -name "*.py")

      - name: Setup Nodejs
        if: matrix.language == 'Nodejs'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies (Nodejs)
        if: matrix.language == 'Nodejs'
        working-directory: front-end
        run: npm ci

      - name: Build (Nodejs)
        if: matrix.language == 'Nodejs'
        working-directory: front-end
        run: npm run build
  
  Test:
    name: Test (${{ matrix.language }})
    runs-on: ubuntu-latest
    needs: [Build]
    strategy:
      fail-fast: false
      matrix:
        language: [Python, Nodejs]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        if: matrix.language == 'Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies (Python)
        if: matrix.language == 'Python'
        working-directory: back-end
        run: pip install -r requirements.txt

      - name: Run Unit & Integration Tests (Python)
        if: matrix.language == 'Python'
        working-directory: back-end
        run: pytest --cov=app --cov-report=term --cov-report=xml --junitxml=report-python.xml

      - name: Setup Nodejs
        if: matrix.language == 'Nodejs'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies (Nodejs)
        if: matrix.language == 'Nodejs'
        working-directory: front-end
        run: npm ci

      - name: Run Unit & Integration Tests (Nodejs)
        if: matrix.language == 'Nodejs'
        working-directory: front-end
        run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: ${{ matrix.language }} Tests
          path: |
            **/report-*.xml
          reporter: java-junit
          fail-on-error: false